name: test-provider
version: "1.0"
summary: Basic dbus provider snap
description: A basic snap declaring a dbus slot
base: core18
grade: stable
confinement: strict

slots:
  dbus-svc:
    interface: dbus
    bus: system
    name: com.hello.world.Demo

apps:
  provider:
    command: bin/provider
    daemon: simple
    slots: [dbus-svc]


parts:
  copy:
    plugin: dump
    source: .

  application:
    plugin: go
    source: .
    build-packages:
      - gcc
